application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      testapp:
        license: Apache-2.0
        actions:
          appdeploy:
            function: actions/appdeploy/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          appio:
            function: actions/appio/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
